AWSTemplateFormatVersion: '2010-09-09'
Description: Article Demo - Secret Manager stack

Parameters:
  EnvironmentParam:
    Type: String

Resources:
  DemoSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: demo-secret
      Description: 'Secret for demo'
      SecretString: "replace with secret"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentParam
        - Key: Application
          Value: demo
